version: '2.3'
services:
  system:
    # image name should be modified to the same with your building version.
    image: "deepmd-kit:latest-cuda-10.0-ubuntu18.04"
    runtime: "nvidia"
    container_name: "deepmd_train"
    # use the following two lines to control the GPUs to use.
    # environment:
    #   - CUDA_VISIBLE_DEVICES=0,1
    # modify the numbers to decide the GPUs to run on.
    volumes:
      - /path/to/example:/root/system
    # the left is local path which could be even a relevant one.
    # the right is target path which should be absolute in container.
    # entering the train folder by default
    working_dir: /root/system/train
    command: 'dp train train.json'